baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme =  'PaperMod'

[menu]
[[menu.main]]
    name = 'Articles'
    url = '/'
    weight = 10
[[menu.main]]
    name = 'Notes'
    url = '/notes'
    weight = 20
[[menu.main]]
    name = 'About'
    url = '/about'
    weight = 30