baseURL = 'veesage.github.io'
languageCode = 'en-us'
title = 'Visage of Vee'
theme =  'PaperMod'

[params]
    ShowReadingTime = true

    [params.analytics]
        [params.analytics.goatCounter]
            code = "veesage"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
    name = 'Articles'
    url = '/'
    weight = 10
[[menu.main]]
    name = 'About'
    url = '/about'
    weight = 20