baseURL = 'veesage.github.io'
languageCode = 'en-us'
title = 'Visage of Vee'
theme =  'PaperMod'

[taxonomies]
  tag = "tags"
  category = "categories" 
  series = "series"

[params]
    ShowReadingTime = true

    [params.analytics]
        [params.analytics.goatCounter]
            code = "veesage"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
[[menu.main]]
    name = 'Articles'
    url = '/'
    weight = 10
[[menu.main]]
    name = 'Series'
    url = '/series'
    weight = 15
[[menu.main]]
    name = 'TIL'
    url = '/til'
    weight = 17
[[menu.main]]
    name = 'About'
    url = '/about'
    weight = 20